name: Commitlint

on: [push, pull_request, workflow_call]

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: ${{ github.workspace }}/.github/workflows/setup.yml
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      # - name: Install system dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get upgrade
      #     sudo apt-get install -y git
      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version-file: '.nvmrc'
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push' # || github.event_name == 'workflow_call'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
