name: Development

on:
  push:
    branches: [master]
  pull_request:

jobs:
  conventional_commits:
    uses: ./.github/workflows/commitlint.yml
  format:
    uses: ./.github/workflows/prettier.yml
  lint:
    uses: ./.github/workflows/eslint.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  integration-tests:
    if: github.event.review.state == 'approved'
    uses: ./.github/workflows/integration-tests.yml
