name: Integration tests

on: [workflow_call]

jobs:
  unit-test:
    name: Integration tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install correct Node.js version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Playwright installation
        run: npx playwright install --with-deps
      - name: Run `e2e` npm script
        run: npm run e2e:ci
