name: Main workflow

on:
  push:
    branches: [master, release/*]
  pull_request:
    branches: [master]

jobs:
  log_default_contexts_to_stdout:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo '$JOB_CONTEXT'
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo '$STEPS_CONTEXT'
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo '$RUNNER_CONTEXT'
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo '$STRATEGY_CONTEXT'
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo '$MATRIX_CONTEXT' 
  # lint:
  #   name: ESLint rules check on Node ${{ matrix.node }} and ${{ matrix.os }} system
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     max-parallel: 2
  #     fail-fast: true
  #     matrix:
  #       include:
  #         - node: 18.16.0
  #           os: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: .
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         repository: ${{ github.repository }}
  #         clean: true
  #         # fetch-depth: 0
  #     - name: Install correct Node.js version
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node }} 
  #         node-version-file: '.nvmrc'
  #         cache: 'npm'
  #         cache-dependency-path: 'package-lock.json'
  #     - run: npm ci
