name: Prettier

on: [push, pull_request, workflow_call]

jobs:
  eslint:
    name: Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: ${{ github.workspace }}/.github/workflows/setup.yml
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      # - name: Install system dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get upgrade
      #     sudo apt-get install -y git
      # - name: Install correct Node.js version
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version-file: '.nvmrc'
      #     cache: 'npm'
      #     cache-dependency-path: 'package-lock.json'
      # - name: Install dependencies
      #   run: npm ci
      - name: Run `format:check` npm script
        run: npm run format:check
