name: Release

on:
  push:
    tags: ['v[0-9]+.?[0-9]*.?[0-9]*']
  workflow_dispatch:

# permissions:
  # issues: write
  # contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Create an issue
        id: create-an-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
          AUTHOR: ${{ github.actor }}
        with:
          filename: ./.github/ISSUE_TEMPLATE.md
          update_existing: true
          search_existing: all
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - if: success()
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-project
          path: ./build
          retention-days: 14
      - if: success()
        name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
