name: Unit tests

on: [push, pull_request, workflow_call]

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install correct Node.js version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run `test-ci` npm script
        run: npm run test-ci
